[package]
name = "itym"
version = "0.1.3"
edition = "2024"
rust-version = "1.95.0"

description = "Specialized tools for your special situations."
categories = ["no-std::no-alloc", "data-structures", "development-tools::debugging", "rust-patterns"]
keywords = ["const", "no_std", "pod"]

license.workspace = true
repository.workspace = true

[dependencies]
itym_assert = { path = "crates/assert", version = "0.1.2", optional = true, }
itym_mem = { path = "crates/mem", version = "0.1.0", optional = true, }
itym_slot = { path = "crates/slot", version = "0.1.2", optional = true, }
itym_str = { path = "crates/str", version = "0.1.0", optional = true, }
itym_ts = { path = "crates/ts", version = "0.1.1", default-features = false, optional = true, }
itym_util = { path = "crates/util", version = "0.1.2", optional = true, }

[features]
default = ["itym_ts?/size_common"]

itym_assert = ["dep:itym_assert"]
itym_assert_shorting = ["itym_assert", "itym_assert/shorting"]

itym_mem = ["dep:itym_mem"]

itym_slot = ["dep:itym_slot"]

itym_str = ["dep:itym_str"]

itym_ts = ["dep:itym_ts"]

itym_util = ["dep:itym_util"]

# Sub-crate
enforce_32bit = ["size_common"]
enforce_64bit = ["size_big"]

size_big = ["itym_ts?/size_big"]
size_common = ["itym_ts?/size_common"]

# Language
alloc = ["itym_slot?/alloc", "itym_str?/alloc"]
std = ["alloc", "itym_slot?/std", "itym_str?/std"]

# Nightly
f16 = ["itym_ts?/f16"]
f128 = ["itym_ts?/f128"]

# 3p Crates
borsh = ["itym_slot?/borsh", "itym_str?/borsh"]
serde = ["itym_slot?/serde", "itym_str?/serde"]

[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
license = "MIT OR Apache-2.0"
repository = "https://github.com/cryotheus/itym"

[workspace.dependencies]
borsh = { version = "1.8.0", default-features = false }
bytemuck = { version = "1.25.2", default-features = false }
serde = { version = "1.0.229", default-features = false }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
	"-Zunstable-options",
	"--generate-link-to-definition",
	"--generate-macro-expansion",
]

