[package]
name = "itym_util"
version = "0.1.1"
edition = "2024"
rust-version = "1.95.0"

description = "Specialized tools for your special situations."
categories = ["no-std::no-alloc"]
# No keywords.
exclude = ["description.md"]

license.workspace = true
repository.workspace = true

[dependencies]
# No depedependencies :D

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
	"-Zunstable-options",
	"--generate-link-to-definition",
	"--generate-macro-expansion",
]
