[package]
name = "itym_slab"
version = "0.1.0"
edition = "2024"
rust-version = "1.95.0"

license.workspace = true
repository.workspace = true

[dependencies]
itym_assert = { path = "../assert", version = "0.1.2", default-features = false, features = ["shorting"] }
#itym_num = { path = "../num" }
#itym_slot = { path = "../slot", version = "0.1.2", default-features = false, features = [] }
itym_ts = { path = "../ts" }

