[package]
name = "itym_num"
version = "0.1.0"
edition = "2024"
rust-version = "1.95.0"

description = ""
categories = []
keywords = []

license.workspace = true
repository.workspace = true

[dependencies]
itym_assert = { version = "0.1.2", features = ["shorting"] }

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = [
	"-Zunstable-options",
	"--generate-link-to-definition",
	"--generate-macro-expansion",
]
