[package]
name = "itym_str"
version = "0.1.0"
edition = "2024"
rust-version = "1.95.0"

description = "Fixed-capacity and fixed-length strings supporting const mutation."
categories = ["no-std::no-alloc", "data-structures", "memory-management", "rust-patterns"]
keywords = ["arraystr", "arraystring"]

license.workspace = true
repository.workspace = true

[dependencies]
itym_assert = { path = "../assert", features = ["shorting"] }
itym_slot = { path = "../slot" }

borsh = { workspace = true, features = [], optional = true }
serde = { workspace = true, features = [], optional = true }

[features]
default = ["std"]
alloc = ["itym_slot/alloc"]
std = ["alloc", "itym_slot/std"]

borsh = ["dep:borsh", "itym_slot/borsh"]
serde = ["dep:serde", "itym_slot/serde"]
