[package]
name = "itym_ts"
version = "0.1.1"
edition = "2024"
rust-version = "1.95.0"

description = "Types for using the type state design pattern."
categories = ["no-std::no-alloc", "rust-patterns"]
keywords = ["typestate"]

license.workspace = true
repository.workspace = true

[dependencies]
# No dependencies :D

[features]
default = ["size_common"]

# Allow casting `n64` to `nsize` during const eval.
# Overflow emits a compile error.
size_big = ["size_common"]

# Allow casting `n32` to `nsize` during const eval
# Overflow emits a compile error.
size_common = []

# Nightly toolchain only
f16 = []
f128 = []

[package.metadata.docs.rs]
features = ["size_big", "size_common"]
rustdoc-args = [
	"-Zunstable-options",
	"--generate-link-to-definition",
	"--generate-macro-expansion",
]
